### ISSUE TITLE
Torrents hang with tracker status "Not contacted yet"

### ISSUE THREAD

**Issue by rlue** [tenseiken/docker-qbittorrent-wireguard#19]
Forgive me; I'm sure I must be missing something obvious here. I can spin up the container and access the web UI no problem, but when I add new torrents, they don't start:

<img width="842" alt="Image" src="https://github.com/user-attachments/assets/e2432960-5a94-4f1e-a505-feb14d42447a" />

### Summary

* Running this container on Debian bookworm (technically DietPi)
* Minimal qBittorrent config customizations vs. default (copied below)
* Web UI is exposed to Internet with Traefik
* Firewall (ufw) set up to allow 8999/tcp and 8999/udp
* No other processes or containers trying to listen on 8999
* VPN is Mullvad; wireguard tunnel verified with

  ```sh
  $ docker exec -it qbittorrent-wireguard curl https://am.i.mullvad.net/connected
  You are connected to Mullvad (server ca-van-wg-202). Your IP address is 104.193.135.110
  ```

Any idea what might be going on? Many thanks in advance.

### The Deets

<details>
<summary><code>docker-compose.yml</code></summary>

```yaml
qbittorrent:
  container_name: qbittorrent
  image: docker.io/tenseiken/qbittorrent-wireguard:latest
  environment:
    PUID: 1000
    PGID: 1000
    LAN_NETWORK: 10.0.0.0/24,fd27:87ab:2c3f::/48
    WEBUI_URL: <REDACTED>
    QBT_LEGAL_NOTICE: confirm
  volumes:
    - ./etc:/config
    - ./data:/downloads
  ports:
    - 8999:8999/tcp
    - 8999:8999/udp
  cap_add:
    - NET_ADMIN
  entrypoint:
    - /bin/bash
    - /start.sh
  ipc: private
  security_opt:
    - label=disable
  stdin_open: true
  sysctls:
    - net.ipv4.conf.all.rp_filter=2
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv6.conf.all.disable_ipv6=0
  tty: true
  working_dir: /opt
  labels:
    traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
    traefik.http.routers.qbittorrent.entrypoints: websecure
    traefik.http.routers.qbittorrent.rule: Host(`<REDACTED>`)
    traefik.http.routers.qbittorrent.tls: true
    traefik.http.routers.qbittorrent.tls.certresolver: letsencrypt
  restart: unless-stopped
```
</details>

<details>
<summary><code>docker container logs -f qbittorrent-wireguard</code></summary>

```log
qbittorrent  | 2025-02-27 19:54:06.485706 [INFO] The container is currently running iptables v1.8.11 (nf_tables).
qbittorrent  | 2025-02-27 19:54:06.517036 [INFO] WireGuard config file is found at /config/wireguard/wg0.conf
qbittorrent  | 2025-02-27 19:54:06.544843 [INFO] VPN remote line defined as '104.193.135.100:51820'
qbittorrent  | 2025-02-27 19:54:06.574662 [INFO] VPN_REMOTE defined as '104.193.135.100'
qbittorrent  | 2025-02-27 19:54:06.610080 [INFO] VPN_PORT defined as '51820'
qbittorrent  | 2025-02-27 19:54:06.641681 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
qbittorrent  | 2025-02-27 19:54:06.672519 [INFO] VPN_DEVICE_TYPE set as 'wg0', since WireGuard will always be wg0.
qbittorrent  | 2025-02-27 19:54:06.703558 [INFO] LAN_NETWORK defined as '10.0.0.0/24,fd27:87ab:2c3f::/48'
qbittorrent  | 2025-02-27 19:54:06.741845 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
qbittorrent  | 2025-02-27 19:54:06.777106 [INFO] Adding 1.1.1.1 to resolv.conf
qbittorrent  | 2025-02-27 19:54:06.813883 [INFO] Adding 8.8.8.8 to resolv.conf
qbittorrent  | 2025-02-27 19:54:06.853856 [INFO] Adding 1.0.0.1 to resolv.conf
qbittorrent  | 2025-02-27 19:54:06.888127 [INFO] Adding 8.8.4.4 to resolv.conf
qbittorrent  | 2025-02-27 19:54:06.917203 [INFO] Starting WireGuard...
qbittorrent  | [#] ip link add wg0 type wireguard
qbittorrent  | [#] wg setconf wg0 /dev/fd/63
qbittorrent  | [#] ip -4 address add <REDACTED> dev wg0
qbittorrent  | [#] ip -6 address add <REDACTED> dev wg0
qbittorrent  | [#] ip link set mtu 1420 up dev wg0
qbittorrent  | [#] resolvconf -a wg0 -m 0 -x
qbittorrent  | could not detect a useable init system
qbittorrent  | [#] wg set wg0 fwmark 51820
qbittorrent  | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
qbittorrent  | [#] ip -4 rule add not fwmark 51820 table 51820
qbittorrent  | [#] ip -4 rule add table main suppress_prefixlength 0
qbittorrent  | [#] iptables-restore -n
qbittorrent  | 2025-02-27 19:54:07.017821 [INFO] Docker network defined as 172.18.0.0/24
qbittorrent  | 2025-02-27 19:54:07.051821 [INFO] Adding 10.0.0.0/24 as route via docker eth0
qbittorrent  | 2025-02-27 19:54:07.085221 [INFO] Adding fd27:87ab:2c3f::/48 as route via docker eth0
qbittorrent  | Error: inet6 address is expected rather than "172.18.0.1".
qbittorrent  | 2025-02-27 19:54:07.113897 [INFO] ip route defined as follows...
qbittorrent  | --------------------
qbittorrent  | default via 172.18.0.1 dev eth0
qbittorrent  | 172.18.0.0/24 dev eth0 proto kernel scope link src 172.18.0.3
qbittorrent  | 192.168.1.0/24 via 172.18.0.1 dev eth0
qbittorrent  | --------------------
qbittorrent  | iptable_mangle         49152  0
qbittorrent  | ip_tables              65536  3 iptable_filter,iptable_raw,iptable_mangle
qbittorrent  | x_tables               81920  22 xt_conntrack,iptable_filter,nft_compat,xt_LOG,xt_multiport,xt_tcpudp,xt_addrtype,xt_recent,xt_nat,ip6t_rt,xt_comment,xt_set,ipt_REJECT,xt_connmark,iptable_raw,ip_tables,xt_limit,xt_hl,xt_MASQUERADE,ip6t_REJECT,iptable_mangle,xt_mark
qbittorrent  | 2025-02-27 19:54:07.148053 [INFO] iptable_mangle support detected, adding fwmark for tables
qbittorrent  | 2025-02-27 19:54:07.353081 [INFO] iptables defined as follows...
qbittorrent  | --------------------
qbittorrent  | -P INPUT DROP
qbittorrent  | -P FORWARD ACCEPT
qbittorrent  | -P OUTPUT DROP
qbittorrent  | -A INPUT -i wg0 -j ACCEPT
qbittorrent  | -A INPUT -s 172.18.0.0/24 -d 172.18.0.0/24 -j ACCEPT
qbittorrent  | -A INPUT -i eth0 -p udp -m udp --sport 51820 -j ACCEPT
qbittorrent  | -A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
qbittorrent  | -A INPUT -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
qbittorrent  | -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
qbittorrent  | -A INPUT -i lo -j ACCEPT
qbittorrent  | -A OUTPUT -o wg0 -j ACCEPT
qbittorrent  | -A OUTPUT -s 172.18.0.0/24 -d 172.18.0.0/24 -j ACCEPT
qbittorrent  | -A OUTPUT -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
qbittorrent  | -A OUTPUT -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
qbittorrent  | -A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
qbittorrent  | -A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
qbittorrent  | -A OUTPUT -o lo -j ACCEPT
qbittorrent  | --------------------
qbittorrent  | 2025-02-27 19:54:07.393644 [WARNING] ENABLE_SSL is set to '', SSL config ignored. No changes made.
qbittorrent  | 2025-02-27 19:54:07.430854 [INFO] Starting qBittorrent daemon...
qbittorrent  | 2025-02-27 19:54:07.977067 [INFO] qBittorrent PID: 239
qbittorrent  | 2025-02-27 19:54:08.007872 [INFO] HEALTH_CHECK_HOST is not set. For now using default host one.one.one.one
qbittorrent  | 2025-02-27 19:54:08.038086 [INFO] HEALTH_CHECK_INTERVAL is not set. For now using default interval of 300
qbittorrent  | 2025-02-27 19:54:08.066287 [INFO] HEALTH_CHECK_SILENT is not set. Because this variable is not set, it will be supressed by default
qbittorrent  | 2025-02-27 19:54:08.096834 [WARNING] RESTART_CONTAINER not defined,(via -e RESTART_CONTAINER), defaulting to 'yes'
qbittorrent  | 2025-02-27 19:54:08.125627 [INFO] HEALTH_CHECK_AMOUNT is not set. For now using default interval of 1
qbittorrent  | 2025-02-27 19:54:08.160022 [INFO] HEALTH_CHECK_AMOUNT is set to 1
```
</details>

<details>
<summary><code>qBittorrent.conf</code></summary>

```ini
[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[BitTorrent]
Session\AddTorrentStopped=false
Session\AnnounceIP=
Session\BTProtocol=Both
Session\DefaultSavePath=/downloads
Session\ExcludedFileNames=
Session\GlobalMaxRatio=5
Session\Interface=wg0
Session\InterfaceAddress=
Session\InterfaceName=wg0
Session\Port=8999
Session\QueueingSystemEnabled=true
Session\SSL\Port=35694
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/temp
Session\TempPathEnabled=true
Session\UseRandomPort=false

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\InetAddress=
Connection\Interface=wg0
Connection\InterfaceAddress=
Connection\InterfaceListenIPv6=false
Connection\InterfaceName=wg0
General\Locale=en
General\UseRandomPort=false
MailNotification\req_auth=true
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=10.0.0.0/24, fd27:87ab:2c3f::/48
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\HostHeaderValidation=true
WebUI\Password_PBKDF2="@ByteArray(<REDACTED>)"
WebUI\Port=8080
WebUI\RootFolder=/etc/vuetorrent
WebUI\ServerDomains=<REDACTED>
WebUI\Username=<REDACTED>

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
```
</details>

<details>
<summary>Web UI execution log</summary>

<img width="799" alt="Image" src="https://github.com/user-attachments/assets/278a18c9-92a0-4fac-bd44-69c620042c1c" />
</details>
