### ISSUE TITLE
Docker Container Not Starting

### ISSUE THREAD

**Issue by ajthom90** [tenseiken/docker-qbittorrent-wireguard#21]
Hello,

I have been troubleshooting this for a few days. I updated my host machine to Ubuntu 25.04 beta running kernel 6.14 on amd64, and ever since upgrading, the container is not starting. I have tried many different versions of the container (4.6.7, 5.0.2, 5.0.3), I've tried modifying and rebuilding the container, and every time I start it, it ends with the /usr/bin/readlink permission denied error. When I re-built the container to put a sleep in, so that I could `docker exec` and run commands, readlink is present. 

I'm fairly new to Docker, so if there's any help you can give to troubleshoot, that would be wonderful! I am still troubleshooting as well and will post if I discover anything.

`bt2  | 2025-04-14 15:59:45.692793 [INFO] The container is currently running iptables v1.8.11 (nf_tables).`
`bt2  | 2025-04-14 15:59:45.712302 [INFO] WireGuard config file is found at /config/wireguard/wg0.conf`
`bt2  | 2025-04-14 15:59:45.731491 [INFO] VPN remote line defined as xxx.xxx.xxx.xxx`
`bt2  | 2025-04-14 15:59:45.748346 [INFO] VPN_REMOTE defined as 'xxx.xxx.xxx.xxx'`
`bt2  | 2025-04-14 15:59:45.766246 [INFO] VPN_PORT defined as '51820'`
`bt2  | 2025-04-14 15:59:45.786315 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.`
`bt2  | 2025-04-14 15:59:45.803460 [INFO] VPN_DEVICE_TYPE set as 'wg0', since WireGuard will always be wg0.`
`bt2  | 2025-04-14 15:59:45.819649 [INFO] LAN_NETWORK defined as '192.168.1.0/24'`
`bt2  | 2025-04-14 15:59:45.836325 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers`
`bt2  | 2025-04-14 15:59:45.852826 [INFO] Adding 1.1.1.1 to resolv.conf`
`bt2  | 2025-04-14 15:59:45.869270 [INFO] Adding 8.8.8.8 to resolv.conf`
`bt2  | 2025-04-14 15:59:45.886602 [INFO] Adding 1.0.0.1 to resolv.conf`
`bt2  | 2025-04-14 15:59:45.902775 [INFO] Adding 8.8.4.4 to resolv.conf`
`bt2  | 2025-04-14 15:59:45.918343 [INFO] Starting WireGuard...`
`bt2  | /usr/bin/wg-quick: line 11: /usr/bin/readlink: Permission denied`

**Comment by ajthom90** [comment]
I just spun up virtual machines of Ubuntu 24.10 server and Ubuntu 25.04 beta server to try and reproduce, and the issue exists when docker is running on 25.04, and not on 24.10 and earlier.

I also realized I forgot to post my docker-compose file.

Thanks again for any help you can provide! I appreciate it!

```
services:
  qbittorrent-wireguard:
    cap_add:
      - "NET_ADMIN"
    container_name: "bt2"
    entrypoint:
      - "/bin/bash"
      - "/start.sh"
    environment:
      - "PUID=1000"
      - "PGID=995"
      - "LAN_NETWORK=192.168.1.0/24"
#      - "ENABLE_SSL=1"
      - "QBT_LEGAL_NOTICE=confirm"
      - "ENABLEPROTONVPNPORTFWD=1"
      - "WEBUI_URL=xxxxxxx"
      - "WEBUI_USER=xxxxxxx"
      - "WEBUI_PASS=xxxxxxx"
    image: "docker.io/tenseiken/qbittorrent-wireguard:latest"
    ipc: "private"
    network_mode: "bridge"
    ports:
      - "8999:8999/tcp"
      - "8999:8999/udp"
      - "8080:8080/tcp"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    stdin_open: true
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv6.conf.all.disable_ipv6=1"
    tty: true
    volumes:
      - "/bt/downloads:/downloads"
      - "/bt/config:/config"
    working_dir: "/opt"

secrets:
  WebUICertificate.crt:
    file: /etc/letsencrypt/live/xxxxxxxx/fullchain.pem
  WebUIKey.key:
    file: /etc/letsencrypt/live/xxxxxxxx/privkey.pem

```
