### ISSUE TITLE
Container does not work - wg-quick issue

### ISSUE THREAD

**Issue by baget** [tenseiken/docker-qbittorrent-wireguard#22]
Hi
I'm running the latest Container and I see the following error:
2025-05-27 17:20:02.981874 [INFO] Starting WireGuard...
/usr/bin/wg-quick: line 11: /usr/bin/readlink: Permission denied

can't find a way to resolve it.
Here is my conf:

```yaml
  qbittorrent-wireguard:
    container_name: "qbittorrent-wireguard"
    image: "docker.io/tenseiken/qbittorrent-wireguard:latest"
    cap_add:
      - "NET_ADMIN"
    entrypoint:
      - "/bin/bash"
      - "/start.sh"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "LAN_NETWORK=192.168.1.0/24"
      - "QBT_LEGAL_NOTICE=confirm"
      - "TZ=Asia/Jerusalem"
      - "ENABLEPROTONVPNPORTFWD=1"
      - "WEBUI_URL=http://testsrv.local:8080/"
      - "WEBUI_USER=xxxx"
      - "WEBUI_PASS=xxxxx"          
    ipc: "private"
    network_mode: "bridge"
    ports:
      - "8999:8999/tcp"
      - "8999:8999/udp"
      - "8080:8080/tcp"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    stdin_open: true
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv6.conf.all.disable_ipv6=1"
    tty: true
    volumes:
      - "/mnt/mystorage-Downloads/:/downloads"
      - "/home/user/docker/qbittorrent-wireguard:/config"
    working_dir: "/opt"
```
